export const GET_MY_SESSIONS_REQUEST = 'app/Dashboard/GET_MY_SESSIONS_REQUEST';
export const GET_MY_SESSIONS_RESPONSE = 'app/Dashboard/GET_MY_SESSIONS_RESPONSE';
export const PRE_START_SESSION = 'app/Dashboard/PRE_START_SESSION';
export const SESSION_STARTED_RESPONSE = 'app/Dashboard/SESSION_STARTED_RESPONSE';
export const SESSION_ENDED_RESPONSE = 'app/Dashboard/SESSION_ENDED_RESPONSE';
